version: 4.1.2

services:
  #  mongo.db:
  #    image: mongo
  #    env_file:
  #      - .env.mongo
  #    ports:
  #      - '27027:27017'
  #    volumes:
  #      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  #      - ./mongo_db:/data/db
  #    restart: on-failure

#  mywql.db:
#    image: mysql
#    env_file:
#      - .env.mysql
#    ports:
#      - '3307:3306'
#    volumes:
#      - ./mysql_db:/var/lib/mysql
#    restart: on-failure

  postgres.db:
    image: postgres:16-alpine
    env_file:
      - .env.postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    restart: on-failure

#  web:
#    image: nginx:alpine
#    ports:
#      - '80:80'
#    volumes:
#      - ./client:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    restart: on-failure
